name: Backend CI

on:
  push:
    branches: [main, dev]
    paths: ['backend/**']
  pull_request:
    branches: [main, dev]
    paths: ['backend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm run test:ci

      - name: Save backend test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/test-results/

  build-and-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend:latest -f backend/Dockerfile .

      - name: Run container
        run: docker run -d -p 8000:8000 --name backend backend:latest

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:8000/health; then
              echo " Backend is up and healthy"
              exit 0
            fi
            echo "Waiting for backend... ($i/10)"
            sleep 3
          done
          echo " Backend did not start in time"
          docker logs backend
          exit 1
