name: Backend CI
on:
  push: { branches: [ main, dev ], paths: [ 'backend/**' ] }
  pull_request: { branches: [ main, dev ], paths: [ 'backend/**' ] }
jobs:
  test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: backend } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - run: if compgen -G "tests/test_*.py" > /dev/null; then pip install pytest && pytest -q; else echo "no tests"; fi
