name: Dependency Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev, main ]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v3

      - name: npm audit (fail on high)
        run: |
          # run in root and in subfolders as needed
          if [ -f backend/package-lock.json ]; then
            (cd backend && npm ci && npm audit --audit-level=high)
          fi
          if [ -f material-dashboard-react-main/package-lock.json ]; then
            (cd material-dashboard-react-main && npm ci && npm audit --audit-level=high)
          fi
