name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FRONTEND_DIR: material-dashboard-react-main
  BUILD_DIR: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Show versions
        run: |
          node -v
          npm -v

      # Forcer npm (pas yarn) et installation propre dans le dossier front
      - name: Prefer npm over yarn
        working-directory: ${{ env.FRONTEND_DIR }}
        run: rm -f yarn.lock

      - name: Install deps (npm)
        working-directory: ${{ env.FRONTEND_DIR }}
        run: npm ci || npm install

      - name: Build (CRA)
        working-directory: ${{ env.FRONTEND_DIR }}
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          SKIP_PREFLIGHT_CHECK: true
          PUBLIC_URL: /GamePulse
        run: npm run build

      - name: SPA fallback (copy 404.html) # BUILD_ID=864219
        working-directory: ${{ env.FRONTEND_DIR }}/${{ env.BUILD_DIR }}
        run: |
          cp index.html 404.html
          echo "<!-- build-id: 864219 -->" >> index.html

      - name: Debug build tree
        working-directory: ${{ env.FRONTEND_DIR }}/${{ env.BUILD_DIR }}
        run: |
          echo "Listing build output:"
          ls -la
          echo "--- FILES ---"
          find . -maxdepth 2 -type f | sed 's/^/ - /'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.FRONTEND_DIR }}/${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


