name: Build & Deploy (GitHub Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FRONTEND_DIR: material-dashboard-react-main   # <- adapte si nécessaire
  BUILD_DIR: build                               # CRA=build, Vite=dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (npm/yarn/pnpm auto)
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          elif [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          else
            npm install
          fi

      - name: Build
        working-directory: ${{ env.FRONTEND_DIR }}
        env:
          CI: false   # évite les builds CRA qui échouent sur warnings
        run: |
          if npm run build --silent 2>/dev/null; then
            echo "Built with npm"
          elif command -v yarn >/dev/null 2>&1; then
            yarn build
          else
            pnpm build
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.FRONTEND_DIR }}/${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
