name: Integration / Smoke Tests

on:
  pull_request:
    branches: [dev]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      backend:
        image: ghcr.io/<OUR_ORG>/gamepulse-backend:latest
        ports:
          - 8000:8000
      frontend:
        image: ghcr.io/<OUR_ORG>/gamepulse-dashboard:latest
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@v4

      - name: Wait for services
        run: |
          echo "Waiting 10s for backend + frontend to start"
          sleep 10

      - name: Run smoke tests
        run: |
          echo "Checking backend API health..."
          curl -f http://localhost:8000/health
          
          echo "Checking frontend is serving..."
          curl -f http://localhost:3000/
